server:
  port: 8083
spring:
  application:
    name: "generator-rpd"

application:
  semester-offset: 8
  waiting-teachers-delay: "PT1S"
  default-report-value: "Необходимо заполнить вручную"
  files:
    department-excel-filename: "departments.xlsx"
    department-txt-filename: "departments.txt"
    plan-filename: "plan.xlsx"
