server:
  port: 8083
spring:
  application:
    name: "generator-rpd"

application:
  semester-offset: ${SEMESTER_OFFSET:8}
  waiting-teachers-delay: ${WAITING_TEACHERS_DELAY:PT1S}
  default-report-value: ${DEFAULT_REPORT_VALUE:Необходимо заполнить вручную}
  files:
    department-excel-filename: "departments.xlsx"
    department-txt-filename: "departments.txt"
    plan-filename: "plan.xlsx"
